import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/nav-bar'
import ServiceProviderSection from '@/components/service-provider/service-provider-section'
import Footer from '@/components/footer/footer'
import HeroBg from '@/components/hero-slide/hero-bg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NavBar />
        <HeroBg />
        <main>{children}</main>
        <ServiceProviderSection />
        <Footer />
      </body>
    </html>
  )
}
